# Generated by Django 5.1.3 on 2024-11-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhombusai', '0002_filetypemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetypemodel',
            name='type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
